#!/bin/sh

# common_image includes some exported vars and check methods
sudo bash ./common_image

# build docker image
cp Dockerfile_mbtci_java${JAVA_MAJOR_VERSION} Dockerfile
sed  -i "s/NODE_VERSION_ARG/v${NODE_VERSION_ARG}/" Dockerfile
echo "Build mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION}"
docker build -t mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} .

# test image
if [ "$JAVA_MAJOR_VERSION" = "11" ] || [ "$JAVA_MAJOR_VERSION" = "8" ] || [ "$JAVA_MAJOR_VERSION" = "17" ]; then
	cp test/goss/goss_template.yaml test/goss/goss.yaml
	sed  -i "s/NODE_VERSION_ARG/v${NODE_VERSION_ARG}/" test/goss/goss.yaml
	docker-compose -f ./docker-compose.test.yml up --build
fi

# cleanup
rm -f Dockerfile
rm -f test/goss/goss.yaml
