#!/bin/sh

# common_image includes some exported vars and check methods
source common_image

# publish image
echo "Publish mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} to $DOCKER_REGISTRY"

docker tag mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION}
docker push ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION}
docker tag mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:latest
docker push ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:latest

